#ifndef __INTERACT_STATUS_HPP
#define __INTERACT_STATUS_HPP

//起始状态
#define INTERACT_STATUS_ROOT 0

//任务同步文件发送请求
#define INTERACT_STATUS_SUBTASK_SYNCFILE_SEND_REQ 100
//任务同步文件发送等待应答
#define INTERACT_STATUS_SUBTASK_SYNCFILE_SEND_WAIT_ACK 101
//任务同步文件发送发送文件
#define INTERACT_STATUS_SUBTASK_SYNCFILE_SEND_SEND 102


#endif //__INTERACT_STATUS_HPP
