#ifndef __INTERACT_STATUS_HPP
#define __INTERACT_STATUS_HPP

//起始状态
#define INTERACT_STATUS_ROOT 0

//任务同步文件发送请求
#define INTERACT_STATUS_SUBTASK_SYNCFILE_SEND_REQ 100
//任务同步文件发送等待应答
#define INTERACT_STATUS_SUBTASK_SYNCFILE_SEND_WAIT_ACK 101
//任务同步文件发送收到对方发来的应答，建立文件传输连接
#define INTERACT_STATUS_SUBTASK_SYNCFILE_SEND_CONNECT 102
//任务同步文件发送建立文件传输连接后等待对方发来开始信号
#define INTERACT_STATUS_SUBTASK_SYNCFILE_SEND_WAIT_START 103
//任务同步文件发送发送文件
#define INTERACT_STATUS_SUBTASK_SYNCFILE_SEND_SEND 104


#endif //__INTERACT_STATUS_HPP
